version: '3.9'
services:
  case-vault-back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  case-vault-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"